
spring:
  application:
    name: authentication-service
  cloud:
    config:
      uri: http://localhost:8888/
management:
  security:
    enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
