server:
  port: 8084
spring:
  application:
    name: payment
  cloud:
    config:
      uri: http://localhost:8888
      import-check.enabled: false
management:
  security:
    enabled: false